- hosts: localhost
  vars_files:
    - settings.yml
  connection: local
  gather_facts: false
  tasks:
    - include: tasks/digitalocean.yml

# Gather node facts (and setup requirements) before setting up PKI.
- hosts: es-nodes
  # Gather facts at the end of the tasks.
  gather_facts: false
  vars_files:
    - settings.yml
  tasks:
    - include: tasks/ansible-requirements.yml

- hosts: localhost
  vars_files:
    - settings.yml
  connection: local
  tasks:
    - include: tasks/pki.yml

- hosts: es-nodes
  vars_files:
    - settings.yml
  tasks:
    - include: tasks/es-node.yml
    - include: tasks/testing.yml