# Provision testing certs/keys on each node and seed the movies 100k data?
- testing: true

# Configure Digital Ocean specifics around node size, region, and number of nodes.
- region: fra1
- num_nodes: 4
- droplet_size: 1gb # 1gb, 512mb

# ES Cluster settings.
# Note that `es_heap_size` must be quite a bit smaller than the `droplet_size` 
# otherwise ES will fail.
- es_heap_size: 500m # 1g, 500m
- cluster_name: test

# Truststore and Keystore passwords.
- ca_pass: asquera
- truststore_pass: asquera

# The users with SSH access to the root account.
- ssh_users:
    andrew:
      key_id: 2724076
    felix:
      key_id: 2724077
    ernesto:
      key_id: 6448725

# The ES users. Generates a client certificate for each.
- client_certificates:
  - admin
  - user

# This doesn't need to be changed.
- token: "{{ lookup('ini', 'api_token section=digital_ocean file=digital_ocean.ini') }}"