- hosts: localhost
  vars_files:
    - settings.yml
  connection: local
  gather_facts: false
  tasks:
    - name: Delete nodes
      register: jobs
      with_sequence: start=1 end={{ num_nodes }}
      digital_ocean:
        command: droplet
        name: "es-node-{{item}}"
        state: absent
        size_id: "{{ droplet_size }}"
        image_id: ubuntu-17-04-x64
        region_id: "{{ region }}"
        unique_name: yes
        api_token: "{{ token }}"
    - name: Clean PKI
      command: ./clean.sh chdir=pki