- name: Wait for port 22 to become available
  local_action: "wait_for port=22 host={{ inventory_hostname }}"

- name: See if requirements exists
  raw: "echo 'import simplejson as json' | python"
  register: has_requirements
  changed_when: false # Just for checking...
  failed_when: false # Python may not exist.

- name: Install ansible requirements
  when: has_requirements.rc != 0
  raw: sudo apt-get -y install python python-simplejson

- name: Gathering facts
  setup: # Gather's facts.